# Tiles
general {
  gaps_in = 0
  gaps_out = 0
  border_size = 0
}

# Launch apps
exec-once = uwsm app -- chromium
exec-once = uwsm app -- code
exec-once = uwsm app -- obsidian
exec-once = uwsm app -- spotify
exec-once = uwsm app -- ghostty
exec-once = uwsm app -- ghostty

# Assign apps to workspaces automatically
windowrule = match:class ^(chromium)$, workspace 2
windowrule = match:class ^(code)$, workspace 3
windowrule = match:class ^(obsidian)$, workspace 4
windowrule = match:class ^(spotify)$, workspace 5

# Inputs
input {
  kb_layout = us,gr
  kb_options = grp:alt_shift_toggle

  natural_scroll = true
}